include: [_pages]

exclude: [LICENSE, README.md, assets/icons/favicon_io.zip, assets/icons/about.txt]

timezone: Canada/Pacific

collections:
    mneyrane:
        permalink: /:title/
        output: true
    projects:
        permalink: /:collection/:title/
        output: true

defaults:
    -
        scope:
            path: ""
        values:
            layout: "mainpage"
    -
        scope:
            path: "_projects"
        values:
            layout: "blog"
